name: nlp_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy<2.0.0
  - pandas
  - pytorch::pytorch
  - pytorch::torchaudio
  - pip:
      - streamlit==1.24.0
      - plotly==5.13.1
      - plotly-express==0.4.1
      - transformers==4.30.2
      - spacy==3.5.3
      - protobuf==3.20.0
      - typing-extensions>=4.0.0
      - pydub==0.25.1
      - jiwer==3.1.0
      - nltk==3.9.1
      - soundfile==0.13.1
  - pip:
      - altair==5.5.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.0
      - attrs==25.3.0
      - blinker==1.9.0
      - blis==1.3.0
      - cachetools==5.5.2
      - catalogue==2.0.10
      - certifi==2025.4.26
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.1.8
      - cloudpathlib==0.21.1
      - coloredlogs==15.0.1
      - comm==0.2.2
      - confection==0.1.5
      - contourpy==1.3.2
      - curated-tokenizers==0.0.9
      - curated-transformers==0.1.1
      - cycler==0.12.1
      - cymem==2.0.11
      - debugpy==1.8.14
      - decorator==5.2.1
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - fonttools==4.58.0
      - fsspec==2025.5.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.0rc1
      - google-api-python-client==2.170.0
      - google-auth==2.40.2
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - grpcio==1.71.0
      - grpcio-status==1.71.0
      - hf-xet==1.1.2
      - httplib2==0.22.0
      - huggingface-hub==0.32.0
      - humanfriendly==10.0
      - idna==3.10
      - ipykernel==6.29.5
      - ipython==8.36.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.1
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - kiwisolver==1.4.8
      - langcodes==3.5.0
      - language-data==1.3.0
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mpmath==1.3.0
      - murmurhash==1.0.13
      - narwhals==1.40.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - omegaconf==2.3.0
      - onnxruntime==1.19.2
      - packaging==24.2
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.3.8
      - preshed==3.0.9
      - prompt-toolkit==3.0.51
      - proto-plus==1.26.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - punctuators==0.0.7
      - pure-eval==0.2.3
      - pyarrow==20.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pydeck==0.9.1
      - pygments==2.19.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - rapidfuzz==3.13.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==14.0.0
      - rpds-py==0.25.1
      - rsa==4.9.1
      - safetensors==0.5.3
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.1.0
      - smmap==5.0.2
      - spacy-curated-transformers==0.3.0
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - stack-data==0.6.3
      - sympy==1.13.1
      - tenacity==9.1.2
      - thinc==8.3.6
      - tokenizers==0.21.1
      - toml==0.10.2
      - torchvision
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typer==0.15.4
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uritemplate==4.1.1
      - urllib3==2.4.0
      - wasabi==1.1.3
      - watchdog==6.0.0
      - wcwidth==0.2.13
      - weasel==0.4.1
      - wrapt==1.17.2